version: '2'

services:
  memcached:
    image: memcached:1.5.7-alpine
    stdin_open: true
    tty: true
    networks:
      awx_net:

  rabbitmq:
    image: rabbitmq:3.7.4-alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: awx
      RABBITMQ_ERLANG_COOKIE: cookiemonster
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: password
    stdin_open: true
    tty: true
    networks:
      awx_net:

  postgres:
    image: postgres:9.6.8-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
      POSTGRES_DB: awx
      POSTGRES_USER: awx
    volumes:
      - awx_db:/var/lib/postgresql/data/pgdata
    stdin_open: true
    tty: true
    networks:
      awx_net:

  awx-web:
    image: stoleas/awx_web:9.3.0
    hostname: awxweb
    stdin_open: true
    tty: true
    user: root
    ports:
      - "8052:8052"
    labels:
      io.rancher.container.pull_image: always
    networks:
      awx_net:
        aliases:
          - devtask

  awx-task:
    image: stoleas/awx_task:9.3.0
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    depends_on:
      - rabbitmq
      - memcached
      - awx-web
      - postgres
    stdin_open: true
    tty: true
    user: root
    labels:
      io.rancher.container.pull_image: always
    networks:
      awx_net:
        aliases:
          - devtask

volumes:
  awx_db:
    driver: local

networks:
  awx_net:
    external: true
