version: '2'

volumes:
  awx-pgdata1:
    driver: local
  awx_config:
    driver: local
  
services:
  memcached:
    image: memcached:1.5.7-alpine
    stdin_open: true
    tty: true

  rabbitmq:
    image: rabbitmq:3.7.4-alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: awx
    stdin_open: true
    tty: true

  postgresql:
    image: postgres:9.6.8-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: awxdatabase
      POSTGRES_PASSWORD: password
      POSTGRES_USER: awx
    stdin_open: true
    tty: true
    volumes_from:
    - postgresql-data
    labels:
      io.rancher.sidekicks: postgresql-data

  postgresql-data:
    image: busybox
    stdin_open: true
    tty: true
    volumes:
    - awx-pgdata1:/var/lib/postgresql/data/pgdata
    labels:
      io.rancher.container.start_once: 'true'

  awx-web:
    image: ansible/awx_web:9.3.0
    hostname: awxweb
    environment:
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: '11211'
    stdin_open: true
    tty: true
    links:
    - postgresql:postgres
    - rabbitmq:rabbitmq
    - memcached:memcached
    volumes_from:
    - awx-config
    user: root
    ports:
      - "8052:8052"

  awx-task:
    image: ansible/awx_task:9.3.0
    hostname: awx
    environment:
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: '11211'
    stdin_open: true
    tty: true
    links:
    - awx-web:web
    - postgresql:postgres
    - rabbitmq:rabbitmq
    - memcached:memcached
    volumes_from:
      - awx-config
    user: root

  awx-config:
    image: stoleas/awx_config:9.3.0
    stdin_open: true
    tty: true
    volumes:
    - awx_config1:/etc/tower/conf.d/environment.sh
    - awx_config1:/etc/tower/conf.d/credentials.py
    - awx_config1:/etc/tower/SECRET_KEY
    labels:
      io.rancher.container.start_once: 'true'