version: '2'
services:
  memcached:
    scale: 1
    start_on_create: true
  awx-web:
    scale: 1
    start_on_create: true
  awx-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: awx-web
        source_port: 8052
        target_port: 8052
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  awx-task:
    scale: 1
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
  postgres-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: postgres
        source_port: 5432
        target_port: 5432
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  postgres-data:
    scale: 1
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5432
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
