version: '2'
services:
  memcached:
    scale: 1
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
  awx-web:
    scale: 1
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
  awx-task:
    scale: 1
    start_on_create: true
